/*
 * BLUETOOTH_config.h
 *
 * Created: 09-Oct-23 3:10:02 PM
 *  Author: SEIF EL_DIN SULTAN 
 */ 


#ifndef BLUETOOTH_CONFIG_H_
#define BLUETOOTH_CONFIG_H_

#define BLUETOOTH_TX_PORT   DIO_PORTD
#define BLUETOOTH_TX_PIN    DIO_PIN1

#define BLUETOOTH_RX_PORT   DIO_PORTD
#define BLUETOOTH_RX_PIN    DIO_PIN0



#endif /* BLUETOOTH_CONFIG_H_ */